# Generated by Django 2.2 on 2021-04-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='traveler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_uploaded', to='belt_app.User'),
        ),
    ]
